import type { JevRequest } from 'decision-lab-sdk';
import original from '../../../examples/jev-review-request.json';
const choice = (instructions: string, options: string[]) => ({ type: 'choice' as const, instructions, criteria: Object.fromEntries(options.map(x => [x, null])) });
const noul = (instructions: string) => ({ type: 'noul' as const, instructions });
export interface Example { id: string; title: string; tag: string; description: string; request: JevRequest }
export const examples: Example[] = [
  { id: 'review', title: 'Review analysis', tag: 'LANGUAGE', description: 'Separate acting quality from the overall sentiment of a review.', request: original as JevRequest },
  { id: 'contrast', title: 'Mixed sentiment', tag: 'COUNTEREXAMPLE', description: 'A positive acting review inside a negative movie review. Try reversing the adjectives.', request: {...original as JevRequest, state: 'The plot was awful and the ending made no sense, but the acting was excellent. The cast gave a wonderful performance.'} },
  { id: 'support', title: 'Support triage', tag: 'ROUTING', description: 'Read the policy and route an incoming support request. These are model predictions, not executed actions.', request: { model: 'decision-lab-v3', state: 'Policy: Billing handles charges and invoices. Technical handles software failures. Sales handles pricing. Urgent means an unresolved outage, security incident, or deadline within 24 hours.\n\nCustomer: Checkout is down for every customer right now. We cannot process any orders. Please investigate immediately. Thank you.', questions: { department: choice('Which department should handle this request?', ['Billing', 'Technical', 'Sales', 'Other']), urgent: noul('Is this request urgent under the stated policy?'), tone: choice('What is the customer tone?', ['Calm', 'Frustrated', 'Angry']) } } },
  { id: 'email', title: 'Email triage', tag: 'PRODUCTIVITY', description: 'Distinguish a personal request from automated marketing urgency.', request: { model: 'decision-lab-v3', state: 'Policy: Route payment matters to Billing, login incidents to Security, promotions to Marketing and project correspondence to Work. An email needs a reply only when it explicitly asks for a personal response. Advertising urgency does not count as urgent.\n\nEmail: LAST CHANCE! Our summer sale ends tonight. Save 30% on all plans. This is an automated newsletter; please do not reply.', questions: { queue: choice('Which queue should handle this email?', ['Billing', 'Security', 'Marketing', 'Work']), reply_needed: noul('Does this email request a personal reply?'), urgent: noul('Is this email urgent under the policy?') } } },
  { id: 'tools', title: 'Tool safety', tag: 'POLICY', description: 'Classify a proposed action. The playground never executes the commands in your text.', request: { model: 'decision-lab-v3', state: 'Policy: Allow read-only inspection and tests explicitly requested by the user. Review unrequested deletion or deployment. Block sending secrets to an untrusted destination.\n\nUser request: Please explain why the service is failing. Do not change anything.\nProposed action: Upload the production .env file containing API secrets to a public debugging site.', questions: { decision: choice('Should this proposed action be allowed, reviewed, or blocked?', ['Allow', 'Review', 'Block']), sends_secrets: noul('Does the proposed action send secrets to an untrusted destination?'), changes_production: noul('Does the proposed action deploy code to production?') } } },
  { id: 'routing', title: 'Model routing', tag: 'AGENTS', description: 'Decide whether a request needs tools or more complex reasoning.', request: { model: 'decision-lab-v3', state: 'Policy: Fast models handle direct extraction and small text edits. Powerful models handle architecture design and multi-step reasoning. Tools are needed only for external information or an external action.\n\nRequest: From this supplied line, return Ben’s score: Ada: 12, Ben: 7. Do not access any other system.', questions: { model: choice('Which model is sufficient under the policy?', ['Fast', 'Powerful']), needs_tools: noul('Does the request require external information or an external action?') } } },
  { id: 'custom', title: 'Start from scratch', tag: 'YOUR EXPERIMENT', description: 'Write a context, define the permitted answers, and inspect the full distribution.', request: { model: 'decision-lab-v3', state: '', questions: { category: choice('Which category best describes this text?', ['Positive', 'Negative', 'Neutral']) } } },
];
export const defaultSchema = { type: 'object', properties: { sentiment: { type: 'string', enum: ['Negative','Positive'], description: 'What is the sentiment of this movie review?' }, good_acting: { type: 'boolean', description: 'Was the acting good?' }, topic: { type: 'string', enum: ['Movies','Sports','Business','Politics'], description: 'What is this text about?' } }, required: ['sentiment','good_acting','topic'], additionalProperties: false };
export const groupNames: Record<string,string> = { support:'Support triage', model_routing:'Model routing', tool_guardrails:'Tool safety', email_triage:'Email triage', document_risk:'Document risk', lead_qualification:'Lead qualification', retrieval_verification:'Retrieval verification' };
