import { icon } from './ui';
const repo='https://github.com/khalilelghoul01/decision-lab';
export const template = `
<a class="skip" href="#workspace">Skip to playground</a>
<aside class="sidebar">
  <a class="brand" href="#playground"><span class="brand-mark">d<span>/</span></span><span>Decision<span class="brand-light">Lab</span><small>AN OPEN EXPERIMENT</small></span></a>
  <div class="nav-label">WORKSPACE</div>
  <nav aria-label="Workspace"><a href="#playground" data-page="playground">${icon('grid')}Playground<span class="nav-key">01</span></a><a href="#testbench" data-page="testbench">${icon('flask')}Test bench<span class="nav-key">02</span></a><a href="#architecture" data-page="architecture">${icon('network')}How it works<span class="nav-key">03</span></a><a href="#developers" data-page="developers">${icon('code')}Developers<span class="nav-key">04</span></a></nav>
  <div class="sidebar-note"><span class="small-label">THE PREMISE</span><p>Read the context once.<br>Score the choices.<br>Let code write the JSON.</p><span class="mini-pill">350M parameters</span></div>
  <div class="sidebar-bottom"><div class="device-status"><i id="gpu-dot" class="dot"></i><span id="device-status">Checking WebGPU…</span></div><a href="${repo}" target="_blank" rel="noreferrer">${icon('github')} Source on GitHub ${icon('external')}</a><small>Built by <a href="https://x.com/BuildWithKhalil" target="_blank" rel="noreferrer">Khalil</a> · Research release 0.1</small></div>
</aside>
<div class="app-shell">
<header class="topbar"><span class="breadcrumb">LAB <span>/</span> <strong id="breadcrumb">PLAYGROUND</strong></span><span class="privacy">${icon('lock')} Prompts stay on your device</span><a class="top-source" href="${repo}" target="_blank" rel="noreferrer">GitHub ${icon('external')}</a></header>
<main id="workspace">
  <div class="page-heading"><div><div class="eyebrow"><span class="live-square"></span> SMALL MODEL. STRUCTURED DECISIONS.</div><h1 id="page-title">The decision playground<span>.</span></h1><p id="page-description">Give it context. Define the possible answers. See what the model thinks.</p></div><span class="experiment-badge">EXPERIMENTAL<span>v0.1 / INT4</span></span></div>
  <section class="model-bar" aria-label="Model loader"><div class="model-symbol">${icon('chip')}</div><div class="model-info"><div class="model-name">Decision Lab 350M <span>INT4</span><span class="status-pill" id="model-state">NOT LOADED</span></div><p id="load-status" role="status">Load the model once to run decisions locally.</p><div class="download-track" hidden id="progress-wrap"><progress id="load-progress" max="1" value="0" aria-label="Current model file download"></progress><span id="load-detail"></span></div></div><div class="model-actions"><button class="button primary" id="load-model">${icon('download')} Load model <span class="button-meta">~301 MB</span></button><button class="button quiet" id="cancel-load" hidden>Cancel</button><button class="button quiet" id="unload-model" hidden>Unload</button><button class="icon-button" id="clear-cache" title="Clear downloaded model cache" aria-label="Clear downloaded model cache">${icon('reset')}</button></div></section>
  <div class="notice error" id="global-error" role="alert" hidden></div>
  <section class="page" data-view="playground">
    <div class="section-line"><span class="small-label">START WITH A SCENARIO</span><span class="muted">Editable examples · real model predictions</span></div><div class="scenario-strip" id="scenarios"></div><p class="scenario-description" id="scenario-description"></p>
    <div class="workspace-grid">
      <section class="panel input-panel"><div class="panel-head"><div><span class="section-number">01</span><h2>Your input</h2></div><div class="segmented" aria-label="Input format"><button data-editor="fields" aria-pressed="true">Builder</button><button data-editor="json" aria-pressed="false">Request JSON</button><button data-editor="schema" aria-pressed="false">JSON Schema</button></div></div>
      <div id="context-block" data-clarity-mask="true"><div class="input-label"><label for="context">CONTEXT</label><span id="context-size">0 characters</span></div><textarea id="context" class="context-input" placeholder="Paste a review, a support ticket, a policy, or your own text…" spellcheck="false"></textarea></div>
      <div id="builder-editor"><div class="input-label"><span>DECISION FIELDS</span><span id="field-count"></span></div><div id="fields" data-clarity-mask="true"></div><button class="add-field" id="add-field">${icon('plus')} Add a field</button></div>
      <div id="json-editor" data-clarity-mask="true" hidden><label class="sr-only" for="request-json">Jev-compatible request JSON</label><textarea id="request-json" class="code-editor" spellcheck="false"></textarea><p class="editor-help">Choice, Noul and Score use Jev-shaped JSON. Inference uses the local Decision Lab model.</p></div>
      <div id="schema-editor" data-clarity-mask="true" hidden><label class="input-label" for="schema-json">OUTPUT JSON SCHEMA</label><textarea id="schema-json" class="code-editor" spellcheck="false"></textarea><p class="editor-help">Flat objects with boolean or enum fields. Descriptions tell the model what to decide.</p></div>
      <div class="run-toolbar"><div><label for="scoring-mode" class="small-label">SCORING MODE</label><select id="scoring-mode"><option value="accurate">Two orders · reduce position bias</option><option value="fast">One order · less work</option></select></div><button class="button primary" id="run-decision" disabled>${icon('play')} Run decision</button></div><div class="panel-foot"><span>Max 32 fields · 2–8 choices · 1,024 tokens per field prompt</span><button class="text-button" id="export-request">Export request ${icon('download')}</button></div>
      </section>
      <section class="panel output-panel" data-clarity-mask="true"><div class="panel-head"><div><span class="section-number">02</span><h2>Model output</h2></div><span class="latency-badge" id="latency-badge">${icon('clock')} — ms</span></div><div class="output-tabs" role="tablist" aria-label="Output format"><button role="tab" aria-selected="true" data-output="visual">Decisions</button><button role="tab" aria-selected="false" data-output="raw">Raw JSON</button><div class="output-actions"><button class="icon-button" id="copy-result" disabled title="Copy response JSON" aria-label="Copy response JSON">${icon('copy')}</button><button class="icon-button" id="export-result" disabled title="Download run details" aria-label="Download run details">${icon('download')}</button></div></div>
      <div id="empty-output" class="empty-state"><div class="empty-diagram"><span>context</span><i>→</i><span class="empty-chip">${icon('chip')}</span><i>→</i><span>{ }</span></div><h3>Decisions, without the typing.</h3><p>Load the model and run a scenario.<br>Each field gets a value and a probability distribution.</p><div class="empty-types"><span>Choice</span><span>Noul</span><span>Score</span></div></div>
      <div id="result-stale" class="notice" hidden>Input changed. These results belong to your previous run.</div><div id="result-visual" hidden></div><pre id="result-raw" class="json-output" hidden></pre><div id="run-metrics" class="run-metrics" hidden></div><div class="output-note">${icon('flask')}<p><strong>Valid JSON ≠ correct decisions.</strong> Probabilities can be confidently wrong. Noul is P(yes); Choice/Score confidence measures distribution concentration.</p></div></section>
    </div>
    <section class="history-section" data-clarity-mask="true"><div class="section-line"><h2>Session history <span id="history-count">0 runs</span></h2><button class="text-button" id="clear-history">Clear history</button></div><div id="history"><p class="muted">Your recent runs appear here. History stays in memory and clears when you reload.</p></div></section>
  </section>
  <section class="page" data-view="testbench" hidden>
    <div class="test-cards"><div class="panel test-card"><span class="eyebrow">01 / YOUR DEVICE</span><h2>Measure the runtime</h2><p>Compare one and two option orders using the current typed request. One warm-up per mode, then five measured requests.</p><button class="button secondary" id="benchmark" disabled>${icon('clock')} Run benchmark</button><div id="benchmark-result" class="test-result"><span class="muted">No timings yet. Model loading is excluded.</span></div></div><div class="panel test-card"><span class="eyebrow">02 / NUMERICAL CHECK</span><h2>Verify the browser export</h2><p>Check tokenizer agreement, answer agreement with the exported Python fixture, and full-context versus shared-cache probabilities.</p><button class="button secondary" id="parity" disabled>${icon('check')} Run reference checks</button><div id="parity-result" class="test-result"><span class="muted">A runtime check, not an accuracy benchmark.</span></div></div></div>
    <section class="panel suite-panel"><div class="panel-head"><div><span class="section-number">03</span><h2>Workflow evaluation</h2></div><span class="mini-pill">84 CORE CASES + 12 STRESS CASES</span></div><div class="suite-intro"><p>Run the published, previously inspected regression suite on your own device. Expected labels are fixed. This does not call Jev, and it is not a fresh blind test.</p><div class="suite-controls"><select id="suite-group" aria-label="Evaluation subset"><option value="core">All core workflows · 84 cases</option><option value="stress">Stress cases · injection & long context</option></select><button class="button primary" id="run-suite" disabled>${icon('play')} Run evaluation</button><button class="button quiet" id="stop-suite" hidden>Stop after this case</button><button class="button quiet" id="export-suite" disabled>${icon('download')} Export</button></div></div><div id="suite-progress" class="suite-progress" role="status">No evaluation run yet.</div><div id="suite-summary"></div><div class="table-scroll"><table class="evaluation-table"><thead><tr><th>Case</th><th>Field accuracy</th><th>Record</th><th>Latency</th><th>Inspect</th></tr></thead><tbody id="suite-rows"></tbody></table></div><details class="suite-mistakes" id="suite-details" hidden><summary>Case details and mistakes</summary><pre id="suite-detail-json"></pre></details></section>
    <div class="published-results"><span class="eyebrow">PUBLISHED RESEARCH BASELINE</span><div><strong>83.0%<span>Held-out public tasks · 1,600 examples</span></strong><strong>59.6%<span>Known workflow field accuracy · WebGPU</span></strong><strong>19.0%<span>Exact workflow records · 16 of 84</span></strong></div><p>These are different evaluations. They do not establish production reliability or superiority to Jev. <a href="${repo}/blob/main/docs/RESULTS.md" target="_blank" rel="noreferrer">Read the methodology ↗</a></p></div>
  </section>
  <section class="page" data-view="architecture" hidden>
    <div class="architecture-intro"><span class="eyebrow">THE IDEA IN ONE MINUTE</span><h2>The answer space is small.<br>So is the output head.</h2><p>A regular language model writes every key, quote and value. This experiment uses a language model to score a known set of answers, then assembles the response in code.</p></div><div class="pipeline"><div><span>01</span>${icon('code')}<h3>Context + questions</h3><p>Each question has 2–8 allowed answers, mapped to the single tokens A–H.</p></div><div><span>02</span>${icon('chip')}<h3>One shared prefill</h3><p>The common prefix is processed once. Attention and convolution state are cached.</p></div><div><span>03</span>${icon('network')}<h3>Independent scores</h3><p>Question suffixes reuse that state. An eight-row answer head scores the options.</p></div><div><span>04</span>${icon('check')}<h3>Typed decisions</h3><p>Temperature-scaled probabilities become Choice, Noul or Score. Code writes JSON.</p></div></div>
    <div class="knowledge-grid"><article class="panel prose"><span class="eyebrow">THE READOUTS</span><h3>Three ways to read a distribution</h3><dl><dt>Choice <code>"Movies"</code></dt><dd>The highest-probability allowed label, with its full distribution.</dd><dt>Noul <code>0.97</code></dt><dd>P(yes), between 0 and 1. It is not “97% certain the model is correct.” The visual boolean uses a 0.5 threshold.</dd><dt>Score <code>1.42</code></dt><dd>The probability-weighted index of ordered labels. With three levels it ranges from 0 to 2. It is not a separate regression model.</dd></dl></article><article class="panel prose"><span class="eyebrow">THE MODEL</span><h3>Small, adapted, and inspectable</h3><dl><dt>LiquidAI / LFM2.5-350M</dt><dd>16 hybrid layers: six attention blocks and ten short-convolution blocks.</dd><dt>Supervised adaptation</dt><dd>Rank-16 LoRA and eight trained answer rows. A held-out calibration split fits temperature. This release is not RLCD.</dd><dt>Browser export</dt><dd>Four-bit matrix weights, FP16 embeddings and caches, FP32 answer head. ONNX Runtime runs locally through WebGPU.</dd></dl></article><article class="panel prose"><span class="eyebrow">WHAT THE TIMINGS MEAN</span><h3>One prefill, then suffix batches</h3><p>This is not one total forward pass. More fields, longer context, and two option orders add work. Initial downloads and shader compilation are separate from warm inference.</p><p>The 92–148 ms reference timing is for a specific four-field request on an M4 Mac mini. Use the test bench to measure your device.</p></article><article class="panel prose"><span class="eyebrow">OPEN QUESTIONS</span><h3>The hard part is being right</h3><p>Independent fields can contradict each other. Confidence can fail on unfamiliar tasks. This model cannot extract arbitrary free text, and the exported input budget is 1,024 tokens per complete field prompt.</p><p>Fresh workflow evaluation, better data, calibration, longer context and consistent fields are useful contribution areas.</p></article></div>
  </section>
  <section class="page" data-view="developers" hidden>
    <div class="developer-grid"><article class="panel prose"><span class="eyebrow">TYPESCRIPT SDK</span><h2>Load once. Decide locally.</h2><p>The same SDK powers the model runtime here. It includes progress reporting, caching, cancellation, request queuing and GPU cleanup.</p><pre class="code-sample" id="sdk-snippet"></pre><a class="button secondary" href="${repo}/blob/main/sdk/README.md" target="_blank" rel="noreferrer">SDK setup and API ${icon('external')}</a></article><article class="panel prose"><span class="eyebrow">BUILD ON THE EXPERIMENT</span><h2>Everything behind the demo</h2><div class="resource-list"><a href="${repo}" target="_blank" rel="noreferrer"><strong>Source repository</strong><span>Python, TypeScript, training and tests ↗</span></a><a href="${repo}/releases/tag/v0.1.0" target="_blank" rel="noreferrer"><strong>Models and downloads</strong><span>INT4 browser model, native adapter and SDK ↗</span></a><a href="${repo}/blob/main/docs/TRAINING.md" target="_blank" rel="noreferrer"><strong>Reproduce the training</strong><span>Dataset construction, audits and Colab workflow ↗</span></a><a href="${repo}/blob/main/docs/RESULTS.md" target="_blank" rel="noreferrer"><strong>Inspect the results</strong><span>Accuracy, calibration, latency and failure cases ↗</span></a><a href="${repo}/blob/main/CONTRIBUTING.md" target="_blank" rel="noreferrer"><strong>Contribute</strong><span>Bring a failing example or a focused improvement ↗</span></a><a href="/diagnostics.html"><strong>Advanced runtime diagnostics</strong><span>Original parity checks and full-cache benchmarks ↗</span></a><a href="/sdk.html"><strong>SDK lifecycle playground</strong><span>Queueing, cancellation, disposal and cached reload ↗</span></a></div></article></div><div class="notice">Source code is MIT. Model weights retain the LFM Open License, including its commercial-use conditions. This independent experiment is inspired by Jev and is unaffiliated with Jev or TypeSafe.</div>
  </section>
  <footer class="page-footer"><span><i class="dot"></i> LOCAL INFERENCE · OPEN RESEARCH</span><span>Made to inspect, break, and improve.</span></footer>
</main></div><div id="toast" class="toast" role="status" hidden></div>`;
